import type { Metadata, NextPage } from "next";
import { DM_Sans as dmSans } from "next/font/google";
import "./globals.css";
import { type ReactNode } from "react";

import { getUser } from "@/db/queries";
import { Menu } from "@/features/menu/components/menu";
import { SignIn } from "@/features/menu/components/sign-in";
import { PlayerProvider } from "@/features/player/components/context";
import { ThemeProvider } from "@/features/theme/components/context";

import {
    ResizablePanel,
    ResizablePanelGroup,
} from "@/components/ui/resizable";

import { PlayerWrapper } from "@/features/player/components/player-wrapper";
import { Content } from "@/components/content";

const FontSans = dmSans({
    variable: "--font-sans",
    subsets: ["latin"],
    weight: "variable",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: NextPage<Readonly<{ children: ReactNode }>> = async ({
    children,
}) => {
    const user = await getUser();

    if (!user) {
        return (
            <html lang="en">
                <ThemeProvider>
                    <body
                        className={`min-h-screen bg-background font-sans antialiased ${FontSans.variable}`}
                    >
                        <div className="relative flex min-h-screen flex-col items-center justify-center">
                            <SignIn />
                        </div>
                    </body>
                </ThemeProvider>
            </html>
        );
    }

    return (
        <html lang="en">
            <ThemeProvider>
                <body
                    className={`min-h-screen bg-background font-sans antialiased ${FontSans.variable}`}
                >
                    <PlayerProvider>
                        <ResizablePanelGroup
                            direction="vertical"
                            className="min-h-screen"
                        >
                            <ResizablePanel
                                minSize={6}
                                defaultSize={6}
                                className="border-b"
                            >
                                <div className="flex h-full items-center">
                                    <Menu />
                                </div>
                            </ResizablePanel>

                            <ResizablePanel defaultSize={87}>
                                <ResizablePanelGroup direction="horizontal">
                                    <Content>{children}</Content>
                                </ResizablePanelGroup>
                            </ResizablePanel>

                            <ResizablePanel
                                minSize={7}
                                defaultSize={7}
                                className="border-t"
                            >
                                <PlayerWrapper />
                            </ResizablePanel>
                        </ResizablePanelGroup>
                    </PlayerProvider>
                </body>
            </ThemeProvider>
        </html>
    );
};

export default RootLayout;
